source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll-redirect-from'
gem 'kramdown'
gem 'pdf-reader'
gem 'roo'
gem 'roo-xls'
gem 'dotenv'
gem 'mailgun-ruby'
gem 'onetime'
